import assert from 'node:assert/strict';
import { createDefaultGameState } from '../src/systems/StoryState.js';
import { getCurrentObjective, getObjectiveView } from '../src/systems/ObjectiveManager.js';

const state = createDefaultGameState();
assert.equal(getCurrentObjective(state, 'room_prologue'), '沿公路寻找避雨处');
state.doorSlammed = true;
assert.equal(getCurrentObjective(state, 'room_main'), '完成供桌仪式：寻找倒头饭（厨房）、火柴（密室）、香（后院）、纸钱（阁楼）');
let view = getObjectiveView(state, 'room_kitchen');
assert.equal(view.local, '根据水槽、灶台与纸人手势还原饭桌座次');
assert.equal(view.completed, false);
assert.equal(view.memory, '父亲死了，我只是回来避雨。');
state.hasRice = true;
view = getObjectiveView(state, 'room_kitchen');
assert.equal(view.completed, true, 'the kitchen is complete once its own rice puzzle is solved');
state.hasRice = false;
state.hasRice = state.hasMatches = state.hasIncense = state.hasSpiritMoney = true;
assert.equal(getCurrentObjective(state, 'room_main'), '还原两段记忆：从旧书房进入学校，从药柜小间进入医院');
view = getObjectiveView(state, 'room_kitchen');
assert.equal(view.completed, true);
view = getObjectiveView(state, 'room_bedroom_me');
assert.equal(view.completed, false);
state.storyFlags.collectedClues.push('diary_mother', 'toy_plane');
view = getObjectiveView(state, 'room_bedroom_me');
assert.equal(view.completed, true);
state.storyFlags.puzzles.school = true;
state.storyFlags.puzzles.hospital = true;
assert.equal(getCurrentObjective(state, 'room_corridor'), '调查走廊里的四张旧照片');
state.storyFlags.photoSetCollected = true;
view = getObjectiveView(state, 'room_corridor');
assert.equal(view.memory, '所有日期都停在十年前的七月十四。');
assert.equal(getCurrentObjective(state, 'room_corridor'), '用地下室钥匙进入地下禁闭室寻找照片缺角');
state.storyFlags.familyPhotoCornerFound = true;
state.storyFlags.familyPhotoAssembled = true;
state.storyFlags.chasePhase = 'active';
assert.equal(getCurrentObjective(state, 'room_backyard'), '躲藏 6 秒，或把完整全家福带回正厅');

console.log('Objective verification passed');
